package perez.nimo.francisco.jdbc.autogenerated.dao;

import java.sql.SQLException;
import java.util.List;

import perez.nimo.francisco.jdbc.autogenerated.model.Department;
import perez.nimo.francisco.jdbc.autogenerated.model.Employee;

public class DepartmentDao extends AbstractDao<Department, Integer> {
    public DepartmentDao() {
        super(Department.class, "departmentId", "department");
    }

    public List<Employee> getEmployees(Department department) throws SQLException {
        return getOneToMany("employee", "department_id", department.getDepartmentId(), Employee.class, "employeeId");
    }
}