package perez.nimo.francisco.jdbc.autogenerated.dao;

import java.sql.SQLException;
import java.util.List;

import perez.nimo.francisco.jdbc.autogenerated.model.Employee;
import perez.nimo.francisco.jdbc.autogenerated.model.Project;

public class ProjectDao extends AbstractDao<Project, Integer> {
    public ProjectDao() {
        super(Project.class, "projectId", "project");
    }

    public List<Employee> getEmployees(Project project) throws SQLException {
        return getManyToMany("project_has_employee", "project_id", "employee_id", project.getProjectId(), Employee.class, "employeeId");
    }
}