package perez.nimo.francisco.jdbc.autogenerated.dao;

import java.sql.SQLException;

import perez.nimo.francisco.jdbc.autogenerated.model.Employee;
import perez.nimo.francisco.jdbc.autogenerated.model.Task;

public class TaskDao extends AbstractDao<Task, Integer> {
    public TaskDao() {
        super(Task.class, "taskId", "task");
    }

    public Employee getEmployee(Task task) throws SQLException {
        return getOneToOne("employee", "task_id", task.getTaskId(), Employee.class, "employeeId");
    }
}