package perez.nimo.francisco.jdbc.autogenerated.dao;

import perez.nimo.francisco.jdbc.autogenerated.model.User;

public class UserDao extends AbstractDao<User, Integer> {
    public UserDao() {
        super(User.class, "userId", "user");
    }
}