package perez.nimo.francisco.jdbc.autogenerated;

import java.sql.SQLException;
import java.util.List;

import perez.nimo.francisco.jdbc.autogenerated.dao.DepartmentDao;
import perez.nimo.francisco.jdbc.autogenerated.dao.EmployeeDao;
import perez.nimo.francisco.jdbc.autogenerated.dao.ProjectDao;
import perez.nimo.francisco.jdbc.autogenerated.dao.TaskDao;
import perez.nimo.francisco.jdbc.autogenerated.model.Department;
import perez.nimo.francisco.jdbc.autogenerated.model.Employee;
import perez.nimo.francisco.jdbc.autogenerated.model.Project;
import perez.nimo.francisco.jdbc.autogenerated.model.Task;

public class Main {
    public static void main(String[] args) {
        EmployeeDao employeeDao = new EmployeeDao();
        TaskDao taskDao = new TaskDao();
        ProjectDao projectDao = new ProjectDao();
        DepartmentDao departmentDao = new DepartmentDao();

        try {

            // Insert a new employee
            Employee employee = new Employee("12345678A");
            employeeDao.insert(employee);
            System.out.println("Inserted employee: " + employee);
            employee = employeeDao.findById(1);

            // Assign a task to the employee
            Task task = new Task(1, "Task Description");
            taskDao.insert(task);
            employeeDao.assignTask(employee, task);
            System.out.println("Assigned task to employee: " + task);

            // Get the task assigned to the employee
            Task assignedTask = employeeDao.getTask(employee);
            System.out.println("Task assigned to employee: " + assignedTask.getName());

            // // Unassign the task from the employee
            // employeeDao.unassignTask(employee);
            // System.out.println("Unassigned task from employee");

            // Assign a project to the employee
            Project project = new Project(1, "Project Description");
            projectDao.insert(project);
            employeeDao.assignProject(employee, project);
            System.out.println("Assigned project to employee: " + project);

            // Get the projects assigned to the employee
            List<Project> projects = employeeDao.getProjects(employee);
            for (Project p : projects) {
                System.out.println("Projects assigned to employee: " + p.getDescription());
            }

            // // Unassign the project from the employee
            // employeeDao.unassignProject(employee, project);
            // System.out.println("Unassigned project from employee");

            // Assign a department to the employee
            Department department = new Department(1, "Department Name");
            departmentDao.insert(department);
            employeeDao.assignDepartment(employee, department);
            System.out.println("Assigned department to employee: " + department);

            // Get the department assigned to the employee
            Department assignedDepartment = employeeDao.getDepartment(employee);
            System.out.println("Department assigned to employee: " + assignedDepartment.getName());

            // // Unassign the department from the employee
            // employeeDao.unassignDepartment(employee);
            // System.out.println("Unassigned department from employee");

            System.out.println(taskDao.getEmployee(taskDao.findById(1)).getDni());

            for (Employee e : projectDao.getEmployees(projectDao.findById(1))) {
                System.out.println(e.getDni());
            }

            for (Employee e : departmentDao.getEmployees(departmentDao.findById(1))) {
                System.out.println(e.getDni());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}